kind: pipeline
type: docker
name: build

steps:
- name: 拉取代码
  image: alpine
  commands:
  - apt install git -y
  - git clone https://github.com/v2board/v2board-docker.git
  - mv v2board-docker v2b
  - cd v2b/
  - git submodule update --init
  - echo '  branch = master' >> .gitmodules
  - git submodule update --remote
